name: ci-golang-workflow
on:
  pull_request:
    branches:
      - master
jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - run: go mod init teste
      - run: go build math.go && ls -la
      - run: cd src && go test
      - run: go run src/math.go

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: user/app:latest